burgers1d:
  domain:
    x: [-1.0, 1.0]
    t: [0.0, 1.0]
  nu: 0.01/np.pi
  in_features: 2 # (x,t)
  out_features: 1

helmholtz2d:
  domain:
    x: [0.0, 1.0]
    y: [0.0, 1.0]
  k: 2.0
  in_features: 3 # (x,y,t) or (x,y); here steady: use (x,y)
  time_dependent: false
  out_features: 1

poisson2d:
  domain:
    x: [0.0, 1.0]
    y: [0.0, 1.0]
  in_features: 2
  out_features: 1