mlp:
  in_features: 2         # e.g., (x,t) for 1D+time; experiments can override
  out_features: 1
  hidden_layers: 6
  hidden_width: 128
  activation: "tanh"     # tanh|relu|sine

fourier_mlp:
  in_features: 2
  out_features: 1
  hidden_layers: 4
  hidden_width: 128
  activation: "tanh"
  fourier_features:
    enabled: true
    m: 64
    sigma: 10.0