_wandb:
    value:
        cli_version: 0.21.1
        e:
            rihh09oakwkh07737yc20le73ffy9384:
                args:
                    - --model_name
                    - mlp
                    - --experiment_name
                    - burgers1d
                    - --common_config
                    - configs/common_config.yaml
                    - --model_config
                    - configs/model/mlp.yaml
                    - --exp_config
                    - configs/experiment/burgers1d.yaml
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "3936290357248"
                        used: "285969248256"
                email: hankyeol@snu.ac.kr
                executable: /usr/bin/python
                git:
                    commit: f2684ed11f7503847bdbed0a59bd60b257bd2e7d
                    remote: https://github.com/HanKyeol0/PINN-Lab.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-8b4e9b3e-9b9a-521f-caf8-af3c06cfc7ed
                    - architecture: Maxwell
                      cudaCores: 3072
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce GTX TITAN X
                      uuid: GPU-56a35bc2-d798-a43f-cd74-6eb01f9c1b85
                host: adc9826ebd34
                memory:
                    total: "67350802432"
                os: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
                program: -m pinnlab.train
                python: CPython 3.10.6
                root: /root/PINN-research/PINN-Lab
                startedAt: "2025-08-10T09:33:23.887358Z"
                writerId: rihh09oakwkh07737yc20le73ffy9384
        m: []
        python_version: 3.10.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.10.6
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
